
interface _GlobalComponents {
      'CommonCookieBanner': typeof import("../components/common/CookieBanner.vue")['default']
    'CommonGridCols': typeof import("../components/common/GridCols.vue")['default']
    'CommonLangSwitcher': typeof import("../components/common/LangSwitcher.vue")['default']
    'CommonThemeSwitcher': typeof import("../components/common/ThemeSwitcher.vue")['default']
    'LayoutSubMenu': typeof import("../components/layout/SubMenu.vue")['default']
    'VButton': typeof import("../UI/components/Button/Button.vue")['default']
    'VCard': typeof import("../UI/components/Card/Card.vue")['default']
    'VCardBody': typeof import("../UI/components/Card/CardBody.vue")['default']
    'VCardFooter': typeof import("../UI/components/Card/CardFooter.vue")['default']
    'VCardHeader': typeof import("../UI/components/Card/CardHeader.vue")['default']
    'VMenuBar': typeof import("../UI/components/MenuBar/index.vue")['default']
    'AdminHeader': typeof import("../apps/dashboard/components/admin/Header.vue")['default']
    'AdminSidebar': typeof import("../apps/dashboard/components/admin/Sidebar.vue")['default']
    'AdminSidebarItem': typeof import("../apps/dashboard/components/admin/SidebarItem.vue")['default']
    'AdminSidebarLink': typeof import("../apps/dashboard/components/admin/SidebarLink.vue")['default']
    'AdminMetricItem': typeof import("../apps/dashboard/components/admin/metric/Item.vue")['default']
    'UnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.3_postcss@8.4.38_rollup@4.18.0_vite@5.2.11_@types+node@20.12.12_sass@1.77.2_7csiaypyopoqwsdag4fwtrrkne/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'CookieControl': typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
    'CookieIframe': typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
    'NuxtTime': typeof import("../node_modules/.pnpm/nuxt-time@0.1.3_rollup@4.18.0/node_modules/nuxt-time/dist/runtime/components/NuxtTime.vue")['default']
    'ScriptGoogleMaps': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
    'ScriptLemonSqueezyButton': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezyButton.vue")['default']
    'ScriptLoadingIndicator': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
    'ScriptStripePricingTable': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
    'ScriptVimeoPlayer': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
    'ScriptYouTubePlayer': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/@storybook-vue+nuxt@0.2.7_@types+node@20.12.12_encoding@0.1.13_eslint@8.57.0_meow@12.1.1_nuxt_bzyovl7r62tzkqxrexwtgnu4q4/node_modules/@storybook-vue/nuxt/dist/runtime/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'NuxtPicture': typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'ColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@4.18.0/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Button': typeof import("primevue/button")['default']
    'Icon': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'IconCSS': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'NuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtIcon': typeof import("../node_modules/.pnpm/nuxt-icons@3.2.1_rollup@4.18.0/node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'UnLazyImage': typeof import("../node_modules/.pnpm/@unlazy+nuxt@0.11.3_rollup@4.18.0/node_modules/@unlazy/nuxt/dist/runtime/components/UnLazyImage.vue")['default']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyCommonCookieBanner': typeof import("../components/common/CookieBanner.vue")['default']
    'LazyCommonGridCols': typeof import("../components/common/GridCols.vue")['default']
    'LazyCommonLangSwitcher': typeof import("../components/common/LangSwitcher.vue")['default']
    'LazyCommonThemeSwitcher': typeof import("../components/common/ThemeSwitcher.vue")['default']
    'LazyLayoutSubMenu': typeof import("../components/layout/SubMenu.vue")['default']
    'LazyVButton': typeof import("../UI/components/Button/Button.vue")['default']
    'LazyVCard': typeof import("../UI/components/Card/Card.vue")['default']
    'LazyVCardBody': typeof import("../UI/components/Card/CardBody.vue")['default']
    'LazyVCardFooter': typeof import("../UI/components/Card/CardFooter.vue")['default']
    'LazyVCardHeader': typeof import("../UI/components/Card/CardHeader.vue")['default']
    'LazyVMenuBar': typeof import("../UI/components/MenuBar/index.vue")['default']
    'LazyAdminHeader': typeof import("../apps/dashboard/components/admin/Header.vue")['default']
    'LazyAdminSidebar': typeof import("../apps/dashboard/components/admin/Sidebar.vue")['default']
    'LazyAdminSidebarItem': typeof import("../apps/dashboard/components/admin/SidebarItem.vue")['default']
    'LazyAdminSidebarLink': typeof import("../apps/dashboard/components/admin/SidebarLink.vue")['default']
    'LazyAdminMetricItem': typeof import("../apps/dashboard/components/admin/metric/Item.vue")['default']
    'LazyUnoIcon': typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.3_postcss@8.4.38_rollup@4.18.0_vite@5.2.11_@types+node@20.12.12_sass@1.77.2_7csiaypyopoqwsdag4fwtrrkne/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
    'LazyCookieControl': typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
    'LazyCookieIframe': typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
    'LazyNuxtTime': typeof import("../node_modules/.pnpm/nuxt-time@0.1.3_rollup@4.18.0/node_modules/nuxt-time/dist/runtime/components/NuxtTime.vue")['default']
    'LazyScriptGoogleMaps': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
    'LazyScriptLemonSqueezyButton': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezyButton.vue")['default']
    'LazyScriptLoadingIndicator': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
    'LazyScriptStripePricingTable': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
    'LazyScriptVimeoPlayer': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
    'LazyScriptYouTubePlayer': typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/@storybook-vue+nuxt@0.2.7_@types+node@20.12.12_encoding@0.1.13_eslint@8.57.0_meow@12.1.1_nuxt_bzyovl7r62tzkqxrexwtgnu4q4/node_modules/@storybook-vue/nuxt/dist/runtime/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
    'LazyColorScheme': typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@4.18.0/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyButton': typeof import("primevue/button")['default']
    'LazyIcon': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyIconCSS': typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtIcon': typeof import("../node_modules/.pnpm/nuxt-icons@3.2.1_rollup@4.18.0/node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
    'LazyUnLazyImage': typeof import("../node_modules/.pnpm/@unlazy+nuxt@0.11.3_rollup@4.18.0/node_modules/@unlazy/nuxt/dist/runtime/components/UnLazyImage.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CommonCookieBanner: typeof import("../components/common/CookieBanner.vue")['default']
export const CommonGridCols: typeof import("../components/common/GridCols.vue")['default']
export const CommonLangSwitcher: typeof import("../components/common/LangSwitcher.vue")['default']
export const CommonThemeSwitcher: typeof import("../components/common/ThemeSwitcher.vue")['default']
export const LayoutSubMenu: typeof import("../components/layout/SubMenu.vue")['default']
export const VButton: typeof import("../UI/components/Button/Button.vue")['default']
export const VCard: typeof import("../UI/components/Card/Card.vue")['default']
export const VCardBody: typeof import("../UI/components/Card/CardBody.vue")['default']
export const VCardFooter: typeof import("../UI/components/Card/CardFooter.vue")['default']
export const VCardHeader: typeof import("../UI/components/Card/CardHeader.vue")['default']
export const VMenuBar: typeof import("../UI/components/MenuBar/index.vue")['default']
export const AdminHeader: typeof import("../apps/dashboard/components/admin/Header.vue")['default']
export const AdminSidebar: typeof import("../apps/dashboard/components/admin/Sidebar.vue")['default']
export const AdminSidebarItem: typeof import("../apps/dashboard/components/admin/SidebarItem.vue")['default']
export const AdminSidebarLink: typeof import("../apps/dashboard/components/admin/SidebarLink.vue")['default']
export const AdminMetricItem: typeof import("../apps/dashboard/components/admin/metric/Item.vue")['default']
export const UnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.3_postcss@8.4.38_rollup@4.18.0_vite@5.2.11_@types+node@20.12.12_sass@1.77.2_7csiaypyopoqwsdag4fwtrrkne/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const CookieControl: typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
export const CookieIframe: typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt-time@0.1.3_rollup@4.18.0/node_modules/nuxt-time/dist/runtime/components/NuxtTime.vue")['default']
export const ScriptGoogleMaps: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
export const ScriptLemonSqueezyButton: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezyButton.vue")['default']
export const ScriptLoadingIndicator: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
export const ScriptStripePricingTable: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
export const ScriptVimeoPlayer: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
export const ScriptYouTubePlayer: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/@storybook-vue+nuxt@0.2.7_@types+node@20.12.12_encoding@0.1.13_eslint@8.57.0_meow@12.1.1_nuxt_bzyovl7r62tzkqxrexwtgnu4q4/node_modules/@storybook-vue/nuxt/dist/runtime/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const NuxtPicture: typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const ColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@4.18.0/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Button: typeof import("primevue/button")['default']
export const Icon: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const IconCSS: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtIcon: typeof import("../node_modules/.pnpm/nuxt-icons@3.2.1_rollup@4.18.0/node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const UnLazyImage: typeof import("../node_modules/.pnpm/@unlazy+nuxt@0.11.3_rollup@4.18.0/node_modules/@unlazy/nuxt/dist/runtime/components/UnLazyImage.vue")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyCommonCookieBanner: typeof import("../components/common/CookieBanner.vue")['default']
export const LazyCommonGridCols: typeof import("../components/common/GridCols.vue")['default']
export const LazyCommonLangSwitcher: typeof import("../components/common/LangSwitcher.vue")['default']
export const LazyCommonThemeSwitcher: typeof import("../components/common/ThemeSwitcher.vue")['default']
export const LazyLayoutSubMenu: typeof import("../components/layout/SubMenu.vue")['default']
export const LazyVButton: typeof import("../UI/components/Button/Button.vue")['default']
export const LazyVCard: typeof import("../UI/components/Card/Card.vue")['default']
export const LazyVCardBody: typeof import("../UI/components/Card/CardBody.vue")['default']
export const LazyVCardFooter: typeof import("../UI/components/Card/CardFooter.vue")['default']
export const LazyVCardHeader: typeof import("../UI/components/Card/CardHeader.vue")['default']
export const LazyVMenuBar: typeof import("../UI/components/MenuBar/index.vue")['default']
export const LazyAdminHeader: typeof import("../apps/dashboard/components/admin/Header.vue")['default']
export const LazyAdminSidebar: typeof import("../apps/dashboard/components/admin/Sidebar.vue")['default']
export const LazyAdminSidebarItem: typeof import("../apps/dashboard/components/admin/SidebarItem.vue")['default']
export const LazyAdminSidebarLink: typeof import("../apps/dashboard/components/admin/SidebarLink.vue")['default']
export const LazyAdminMetricItem: typeof import("../apps/dashboard/components/admin/metric/Item.vue")['default']
export const LazyUnoIcon: typeof import("../node_modules/.pnpm/@unocss+nuxt@0.60.3_postcss@8.4.38_rollup@4.18.0_vite@5.2.11_@types+node@20.12.12_sass@1.77.2_7csiaypyopoqwsdag4fwtrrkne/node_modules/@unocss/nuxt/runtime/UnoIcon.vue")['default']
export const LazyCookieControl: typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieControl.vue")['default']
export const LazyCookieIframe: typeof import("../node_modules/.pnpm/@dargmuesli+nuxt-cookie-control@8.3.3_rollup@4.18.0_webpack@5.91.0_esbuild@0.20.2_/node_modules/@dargmuesli/nuxt-cookie-control/dist/runtime/components/CookieIframe.vue")['default']
export const LazyNuxtTime: typeof import("../node_modules/.pnpm/nuxt-time@0.1.3_rollup@4.18.0/node_modules/nuxt-time/dist/runtime/components/NuxtTime.vue")['default']
export const LazyScriptGoogleMaps: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptGoogleMaps.vue")['default']
export const LazyScriptLemonSqueezyButton: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLemonSqueezyButton.vue")['default']
export const LazyScriptLoadingIndicator: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptLoadingIndicator.vue")['default']
export const LazyScriptStripePricingTable: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptStripePricingTable.vue")['default']
export const LazyScriptVimeoPlayer: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptVimeoPlayer.vue")['default']
export const LazyScriptYouTubePlayer: typeof import("../node_modules/.pnpm/@nuxt+scripts@0.4.3_@nuxt+devtools@1.3.1_@unocss+reset@0.60.3_floating-vue@5.2.2_@nuxt+kit@3._6ts7q74kli5sakxdmkzard7g4a/node_modules/@nuxt/scripts/dist/runtime/components/ScriptYouTubePlayer.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/@nuxt+ui-templates@1.3.4/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/@storybook-vue+nuxt@0.2.7_@types+node@20.12.12_encoding@0.1.13_eslint@8.57.0_meow@12.1.1_nuxt_bzyovl7r62tzkqxrexwtgnu4q4/node_modules/@storybook-vue/nuxt/dist/runtime/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-img")['default']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/@nuxt+image@1.7.0_ioredis@5.4.1_rollup@4.18.0/node_modules/@nuxt/image/dist/runtime/components/nuxt-picture")['default']
export const LazyColorScheme: typeof import("../node_modules/.pnpm/@nuxtjs+color-mode@3.4.1_rollup@4.18.0/node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyButton: typeof import("primevue/button")['default']
export const LazyIcon: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyIconCSS: typeof import("../node_modules/.pnpm/nuxt-icon@0.6.10_nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12_jxtntewwdssv5p3iyt44weljrq/node_modules/nuxt-icon/dist/runtime/IconCSS.vue")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/.pnpm/@nuxtjs+i18n@8.3.1_rollup@4.18.0_vue@3.4.27_typescript@5.4.5_/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtIcon: typeof import("../node_modules/.pnpm/nuxt-icons@3.2.1_rollup@4.18.0/node_modules/nuxt-icons/dist/runtime/components/nuxt-icon.vue")['default']
export const LazyUnLazyImage: typeof import("../node_modules/.pnpm/@unlazy+nuxt@0.11.3_rollup@4.18.0/node_modules/@unlazy/nuxt/dist/runtime/components/UnLazyImage.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.11.2_@opentelemetry+api@1.8.0_@parcel+watcher@2.4.1_@types+node@20.12.12_@unocss+reset_h7mcoc2ebmazgsca6qpbz5rcxi/node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
